<?php

namespace Database\Seeders;

use App\Models\CommunityMember;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserCommunityMemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Albert Tedjawirawan',
                'email' => 'albert.fresco@gmail.com',
                'phone' => '081519916104',
                'join_date' => '2024-10-14 16:57:41',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Risqi Septiandika',
                'email' => 'risqiseptiandika9989@gmail.com',
                'phone' => '085959697959',
                'join_date' => '2024-10-14 16:57:42',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Unggul',
                'email' => 'pamungkas.unggul@gmail.com',
                'phone' => '08997450547',
                'join_date' => '2024-10-14 16:58:35',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Reza faruoqi',
                'email' => 'oqifaruoqi@gmail.com',
                'phone' => '081381261346',
                'join_date' => '2024-10-29 16:42:12',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Mohamad Arif',
                'email' => 'ahmad.arif22@gmail.com',
                'phone' => '081513110111',
                'join_date' => '2024-10-14 17:50:21',
                'position' => 'Tengah',
                'jersey' => 'Gold, Tidak Punya Semua',
            ],
            [
                'name' => 'Nanang s',
                'email' => 'nanang.setia.ns@gmail.com',
                'phone' => '083813634042',
                'join_date' => '2024-10-14 17:00:44',
                'position' => 'Tengah',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Chairudin',
                'email' => 'hairudin010679@gmail.com',
                'phone' => '081906111468',
                'join_date' => '2024-10-14 17:00:45',
                'position' => 'Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Ardie',
                'email' => 'sunardiardi19@gmail.com',
                'phone' => '081284932124',
                'join_date' => '2024-10-14 17:01:38',
                'position' => 'GK',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Dicky Darmawan',
                'email' => 'dickydarmawann26@gmail.com',
                'phone' => '081298092108',
                'join_date' => '2024-10-14 17:02:12',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Amin Akbar',
                'email' => 'aminakbar.8@gmail.com',
                'phone' => '081574174371',
                'join_date' => '2024-10-14 17:04:21',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Anes',
                'email' => 'yohanes.georgia@gmail.com',
                'phone' => '081299330070',
                'join_date' => '2024-10-14 17:04:24',
                'position' => 'Belakang',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Agus23',
                'email' => 'koer4gus@gmail.com',
                'phone' => '08119835683',
                'join_date' => '2024-10-14 17:05:40',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Harris',
                'email' => 'harris.suryono@gmail.com',
                'phone' => '085717650308',
                'join_date' => '2024-10-14 17:06:12',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'RENSYAH',
                'email' => 'mrennosyahputra@gmail.com',
                'phone' => '081294574230',
                'join_date' => '2024-10-15 12:25:59',
                'position' => 'Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Daru Sasongko',
                'email' => 'dr.sasongko@gmail.com',
                'phone' => '081286130372',
                'join_date' => '2024-10-14 17:07:16',
                'position' => 'Tengah, Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Dhien Alfath Aulya',
                'email' => 'alfath.aulya@gmail.com',
                'phone' => '081291083910',
                'join_date' => '2024-10-14 17:07:18',
                'position' => 'Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Farham Harvianto',
                'email' => 'farhamapple@gmail.com',
                'phone' => '085714481137',
                'join_date' => '2024-10-14 17:07:25',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Satrio Azmi',
                'email' => 'satrioazmialsa@gmail.com',
                'phone' => '087897777580',
                'join_date' => '2024-10-14 17:08:08',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Muhammad Rizki Fadhil (Kiki)',
                'email' => 'kikisembit06@gmail.com',
                'phone' => '081296886296',
                'join_date' => '2024-10-14 17:09:58',
                'position' => 'Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Sedayu',
                'email' => 'sedayux@gmail.com',
                'phone' => '085691046013',
                'join_date' => '2024-10-14 17:10:43',
                'position' => 'GK, Belakang, Tengah, Depan',
                'jersey' => 'Gold, Merah',
            ],
            [
                'name' => 'Fauzan Adhari',
                'email' => 'fauzanyoza29@gmail.com',
                'phone' => '081262001205',
                'join_date' => '2024-10-14 17:12:27',
                'position' => 'Depan',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Suprizano',
                'email' => 'taqizano20@gmail.com',
                'phone' => '08176678600',
                'join_date' => '2024-10-14 17:12:09',
                'position' => 'GK',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Hendri Susilo',
                'email' => 'hensu.bnis@gmail.com',
                'phone' => '082122559933',
                'join_date' => '2024-10-14 17:31:32',
                'position' => 'Belakang',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Pardo',
                'email' => 'supardo1988@gmail.com',
                'phone' => '082299624171',
                'join_date' => '2024-10-14 17:14:08',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Muhammad Iqbal Aulia',
                'email' => 'iqballaulia@gmail.com',
                'phone' => '08990086611',
                'join_date' => '2024-10-14 17:18:08',
                'position' => 'Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Nata',
                'email' => 'franatams@gmail.com',
                'phone' => '081320752239',
                'join_date' => '2024-10-14 17:31:16',
                'position' => 'Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Ricky',
                'email' => 'ciripa1789@gmail.com',
                'phone' => '082122989938',
                'join_date' => '2024-10-14 17:28:18',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Rizky FC',
                'email' => 'freddycapri@gmail.com',
                'phone' => '085966725023',
                'join_date' => '2024-10-14 17:29:57',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Joan Antonio Marcello De Pizzicato',
                'email' => 'merakvila15@gmail.com',
                'phone' => '082111702139',
                'join_date' => '2024-10-14 17:30:21',
                'position' => 'GK',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Aditya Reza Azzindani Putra',
                'email' => 'mr.adityareza@gmail.com',
                'phone' => '081286677404',
                'join_date' => '2024-10-14 17:30:24',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'yanarazor',
                'email' => 'yanarazor@gmail.com',
                'phone' => '082260195526',
                'join_date' => '2024-10-14 17:32:13',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Reiza Wibowo',
                'email' => 'reizawibowo21@gmail.com',
                'phone' => '081287572629',
                'join_date' => '2024-10-14 17:32:39',
                'position' => 'Tengah, Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Khoerul Umam',
                'email' => 'khoerulumam89@gmail.com',
                'phone' => '085782174407',
                'join_date' => '2024-10-14 17:34:28',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Dede supriadi',
                'email' => 'dedrsupriadi888@gmail.com',
                'phone' => '081290737397',
                'join_date' => '2024-10-14 17:36:31',
                'position' => 'Belakang',
                'jersey' => 'Biru',
            ],
            [
                'name' => 'Aris Septiandi',
                'email' => 'septiandi.aris@gmail.com',
                'phone' => '085885586800',
                'join_date' => '2024-10-14 17:36:58',
                'position' => 'Belakang',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Nedi Hendra',
                'email' => 'nedi.hdr@gmail.com',
                'phone' => '081315955891',
                'join_date' => '2024-10-14 17:37:20',
                'position' => 'GK',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Rizki Afriandi',
                'email' => 'r.afriandi@gmail.com',
                'phone' => '085692777004',
                'join_date' => '2024-10-14 17:38:57',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Misbachul choir',
                'email' => 'misbachul.choir@gmail.com',
                'phone' => '081389917732',
                'join_date' => '2024-10-14 17:39:17',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Obeh',
                'email' => 'topanismail07@gmail.com',
                'phone' => '087808432407',
                'join_date' => '2024-10-14 17:41:07',
                'position' => 'Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Farid Rahman',
                'email' => 'fr.farid.rahman@gmail.com',
                'phone' => '081299266009',
                'join_date' => '2024-10-14 17:42:35',
                'position' => 'Tengah',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Dedy Purwanto',
                'email' => 'bungdedy@gmail.com',
                'phone' => '085888800410',
                'join_date' => '2024-10-14 17:50:16',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Alunk Rangkuti',
                'email' => 'elevenalunk@gmail.com',
                'phone' => '081212746417',
                'join_date' => '2024-10-14 17:51:53',
                'position' => 'GK',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Herotz',
                'email' => 'herykholic@gmail.com',
                'phone' => '085691844761',
                'join_date' => '2024-10-14 17:54:24',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Nanang Firmansyah',
                'email' => 'nanang.firmansyah@gmail.com',
                'phone' => '081572003715',
                'join_date' => '2024-10-14 18:04:16',
                'position' => 'Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Feri',
                'email' => 'ferianto.dj@gmail.com',
                'phone' => '0817794591',
                'join_date' => '2024-10-14 18:07:44',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'pandu jago renang',
                'email' => 'pandu.s.kom@gmail.com',
                'phone' => '081280162722',
                'join_date' => '2024-10-14 18:14:17',
                'position' => 'Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Hamal musito',
                'email' => 'hamalmusito@gmail.com',
                'phone' => '085691634244',
                'join_date' => '2024-10-14 18:21:37',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Leonaldiftha Radith',
                'email' => 'pradiftharadith7@gmail.com',
                'phone' => '081212007507',
                'join_date' => '2024-10-14 18:29:32',
                'position' => 'Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Untung Handayani Ramli',
                'email' => 'untung.handayani.ramli@gmail.com',
                'phone' => '081297134870',
                'join_date' => '2024-10-14 18:41:33',
                'position' => 'Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Novanda Reza',
                'email' => 'novandareza89@gmail.com',
                'phone' => '082310887118',
                'join_date' => '2024-10-14 19:13:22',
                'position' => 'Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Imam mardina',
                'email' => 'imamdotmardina@gmail.com',
                'phone' => '081315007806',
                'join_date' => '2024-10-14 19:35:39',
                'position' => 'GK',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Nicky Aditya',
                'email' => 'nickyaditya89@gmail.com',
                'phone' => '085697566622',
                'join_date' => '2024-10-14 19:43:29',
                'position' => 'Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Gelar',
                'email' => 'gelargilang@gmail.com',
                'phone' => '082128555569',
                'join_date' => '2024-10-14 19:45:51',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Alvaro Fajrin Recoba',
                'email' => 'kurnein.fajrin20@gmail.com',
                'phone' => '082123770046',
                'join_date' => '2024-10-14 20:01:08',
                'position' => 'Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Ikbal Fauzi',
                'email' => 'ikbaljune567@gmail.com',
                'phone' => '081219300969',
                'join_date' => '2024-10-29 17:47:15',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Pasca',
                'email' => 'pascapublic@gmail.com',
                'phone' => '08159217195',
                'join_date' => '2024-10-14 20:07:01',
                'position' => 'GK',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Ardino Yosland',
                'email' => 'yosland90@gmail.com',
                'phone' => '081258675525',
                'join_date' => '2024-10-14 20:17:49',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Ekky cahya putra',
                'email' => 'ekkycahyaputra70@gmail.com',
                'phone' => '085210642747',
                'join_date' => '2024-10-15 08:27:13',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Angga Rizal',
                'email' => 'anggarizalnurhuda@gmail.com',
                'phone' => '08567167257',
                'join_date' => '2024-10-15 08:30:55',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Andry pras',
                'email' => 'andry.uinjkt07@gmail.com',
                'phone' => '082298688386',
                'join_date' => '2024-10-15 08:44:05',
                'position' => 'Tengah',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Thesar',
                'email' => 'adelinothesaria@gmail.com',
                'phone' => '081802182283',
                'join_date' => '2024-10-15 10:56:23',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Dimas Hidayat',
                'email' => 'dimashidayat90@gmail.com',
                'phone' => '081294426896',
                'join_date' => '2024-10-15 11:16:17',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Priangga Kuswibowo',
                'email' => 'scootdeeps@gmail.com',
                'phone' => '081319760399',
                'join_date' => '2024-10-15 11:20:34',
                'position' => 'Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Imam Prasetyo',
                'email' => 'imammoslemm@gmail.com',
                'phone' => '085697495420',
                'join_date' => '2024-10-15 11:59:59',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Biru, Gold, Merah',
            ],
            [
                'name' => 'Abdi Putra',
                'email' => 'abdikusumanegaraputra@gmail.com',
                'phone' => '081235382681',
                'join_date' => '2024-10-15 12:04:38',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Daniel Yulianto',
                'email' => 'valen.joscollection@gmail.com',
                'phone' => '081380879469',
                'join_date' => '2024-10-15 12:10:23',
                'position' => 'Belakang, Depan',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Surya Adi Putra',
                'email' => 'suryaady300@gmail.com',
                'phone' => '085691204883',
                'join_date' => '2024-10-15 12:15:01',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Bagus Anugrah',
                'email' => 'bagusanugrah2505@gmail.com',
                'phone' => '082288067060',
                'join_date' => '2024-10-15 12:25:26',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Rashif ali',
                'email' => 'rashifali7@gmail.com',
                'phone' => '081229594961',
                'join_date' => '2024-10-15 12:25:57',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Anggi subekti',
                'email' => 'anggi.subekti@gmail.com',
                'phone' => '082211001423',
                'join_date' => '2024-10-15 12:44:44',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Arianto Hidayat',
                'email' => 'ariantohidayat.ah@gmail.com',
                'phone' => '085773338383',
                'join_date' => '2024-10-15 12:49:34',
                'position' => 'GK, Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Ilmi',
                'email' => 'mochammad.nahrulilmi@gmail.com',
                'phone' => '081385943505',
                'join_date' => '2024-10-15 12:50:31',
                'position' => 'GK',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Raafiansyah Putra',
                'email' => 'rafiansyah05@gmail.com',
                'phone' => '082211739321',
                'join_date' => '2024-10-15 12:52:15',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'ridlo',
                'email' => 'taufikridlo18@gmail.com',
                'phone' => '085730976411',
                'join_date' => '2024-10-15 12:55:08',
                'position' => 'Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Krisna',
                'email' => 'sri.endarnoto@gmail.com',
                'phone' => '08569000990',
                'join_date' => '2024-10-15 13:01:14',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Dewangga Djatmika',
                'email' => 'djatmika.dewangga@gmail.com',
                'phone' => '082120221266',
                'join_date' => '2024-10-15 13:03:40',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Aries Budi Kurniawan',
                'email' => 'aries.budi.kurniawan@gmail.com',
                'phone' => '08121017591',
                'join_date' => '2024-10-15 14:32:27',
                'position' => 'Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'RULIYAN AKBAR',
                'email' => 'ruliyan.akbar@gmail.com',
                'phone' => '087889618485',
                'join_date' => '2024-10-15 16:10:14',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Hamim Ben Arfa',
                'email' => 'hamim.benarfa@gmail.com',
                'phone' => '085881334431',
                'join_date' => '2024-10-15 16:21:09',
                'position' => 'Tengah',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Arli',
                'email' => 'fatkhurahmanarliansyah@gmail.com',
                'phone' => '087781834783',
                'join_date' => '2024-10-15 16:26:53',
                'position' => 'Tengah',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Moch. Fachrur Rozzi',
                'email' => 'fachrur6492@gmail.com',
                'phone' => '081280380020',
                'join_date' => '2024-10-15 16:29:08',
                'position' => 'Tengah',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Dharma F',
                'email' => 'sidewa09@gmail.com',
                'phone' => '081354924944',
                'join_date' => '2024-10-15 16:31:05',
                'position' => 'GK',
                'jersey' => 'Merah',
            ],
            [
                'name' => 'Iqbal Baloo',
                'email' => 'ibalobalo@gmail.com',
                'phone' => '087781944429',
                'join_date' => '2024-10-15 17:09:37',
                'position' => 'Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Buceks Rizal',
                'email' => 'rizal.imora137@gmail.com',
                'phone' => '081290872996',
                'join_date' => '2024-10-20 11:40:55',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Dwi Rezky',
                'email' => 'soebagjodwi@gmail.com',
                'phone' => '082188988668',
                'join_date' => '2024-10-15 20:21:19',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'ADITYA RAHADI',
                'email' => 'adityarahadi27@gmail.com',
                'phone' => '087860500482',
                'join_date' => '2024-10-15 20:53:51',
                'position' => 'GK',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Pawenang Pepeng',
                'email' => 'pawenang.kaloko@gmail.com',
                'phone' => '082114334352',
                'join_date' => '2024-10-15 21:23:29',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Akmal Kautsar P',
                'email' => 'akmalkautsar15@gmail.com',
                'phone' => '087808104615',
                'join_date' => '2024-10-15 21:29:42',
                'position' => 'Tengah, Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Reza devara',
                'email' => 'rezadevara@gmail.com',
                'phone' => '08988981416',
                'join_date' => '2024-10-16 06:04:12',
                'position' => 'Belakang',
                'jersey' => 'Gold, Putih',
            ],
            [
                'name' => 'Awan',
                'email' => 'trianggonosetiawan@gmail.com',
                'phone' => '081287914719',
                'join_date' => '2024-10-16 14:42:05',
                'position' => 'Belakang',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Ginanjar Utardi',
                'email' => 'ginanjarutardi@gmail.com',
                'phone' => '085697268327',
                'join_date' => '2024-10-17 22:12:45',
                'position' => 'Depan',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Fauzi Rahmad',
                'email' => 'amsaazafran@gmail.com',
                'phone' => '0817428665',
                'join_date' => '2024-10-19 10:16:33',
                'position' => 'Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'rudi indriawan',
                'email' => 'rudiindriawan25@gmail.com',
                'phone' => '081293687446',
                'join_date' => '2024-10-20 11:40:38',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Reno Ghanes S',
                'email' => 'renoghanessatria@gmail.com',
                'phone' => '08119393335',
                'join_date' => '2024-10-20 11:47:44',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Hafidz Nurizal',
                'email' => 'hafidznurizal@gmail.com',
                'phone' => '081283852143',
                'join_date' => '2024-10-20 11:49:48',
                'position' => 'Depan',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Danar amrizal',
                'email' => 'danarbutik@gmail.com',
                'phone' => '081808322485',
                'join_date' => '2024-10-20 11:59:55',
                'position' => 'Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Achmad Winandianto',
                'email' => 'awinandianto@gmail.com',
                'phone' => '081291657780',
                'join_date' => '2024-10-29 17:00:32',
                'position' => 'GK',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Bagus Mashurul',
                'email' => 'bmashurul@gmail.com',
                'phone' => '085718212136',
                'join_date' => '2024-10-29 17:01:39',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Putih',
            ],
            [
                'name' => 'Kus Andriadi',
                'email' => 'kaa.daftarbebas@gmail.com',
                'phone' => '085692509990',
                'join_date' => '2024-10-29 17:12:37',
                'position' => 'Belakang, Tengah, Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Ahmad Jaenal Ilham',
                'email' => 'bastian.ilham@gmail.com',
                'phone' => '08987503222',
                'join_date' => '2024-10-29 17:18:56',
                'position' => 'Depan',
                'jersey' => 'Biru',
            ],
            [
                'name' => 'Fazrie Taufik Lubis',
                'email' => 'fazrie@gmail.com',
                'phone' => '081276079898',
                'join_date' => '2024-10-29 17:21:53',
                'position' => 'Belakang',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Arif Alfian',
                'email' => 'arifalfian90@gmail.com',
                'phone' => '085711100160',
                'join_date' => '2024-10-29 17:32:23',
                'position' => 'Belakang',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Bagawarman',
                'email' => 'hellobagawarman@gmail.com',
                'phone' => '081293320172',
                'join_date' => '2024-10-29 17:33:59',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Aydhil',
                'email' => 'aydhila3@gmail.com',
                'phone' => '08998122674',
                'join_date' => '2024-10-29 18:08:15',
                'position' => 'Belakang, Depan',
                'jersey' => 'Biru, Gold, Putih',
            ],
            [
                'name' => 'Murdiansyah',
                'email' => 'murdiansyahp@gmail.com',
                'phone' => '087776265783',
                'join_date' => '2024-10-29 18:45:50',
                'position' => 'Tengah, Depan',
                'jersey' => 'Biru',
            ],
            [
                'name' => 'Davi Pratama',
                'email' => 'davipuratama@gmail.com',
                'phone' => '081315168829',
                'join_date' => '2024-10-29 19:42:18',
                'position' => 'GK',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Annur Syahdyanto',
                'email' => 'annurysm@gmail.com',
                'phone' => '085697008992',
                'join_date' => '2024-10-29 20:07:35',
                'position' => 'Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Aziz Baskoro',
                'email' => 'baskoro.ipsc@gmail.com',
                'phone' => '085776618845',
                'join_date' => '2024-10-29 20:10:46',
                'position' => 'Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Arindi Julian',
                'email' => 'arindijulian8@gmail.com',
                'phone' => '081314051488',
                'join_date' => '2024-10-30 07:22:59',
                'position' => 'Belakang',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Lingga Saputra',
                'email' => 'linggasaputra24@gmail.com',
                'phone' => '082121708033',
                'join_date' => '2024-10-30 08:35:43',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Rendy Ferdiansyah',
                'email' => 'rendy.ferdiansyah1985@gmail.com',
                'phone' => '08128838062',
                'join_date' => '2024-10-30 09:54:15',
                'position' => 'Tengah',
                'jersey' => 'Gold',
            ],
            [
                'name' => 'Indra Wicaksono',
                'email' => 'imlawicaksono@gmail.com',
                'phone' => '081280081196',
                'join_date' => '2024-10-30 09:54:15',
                'position' => 'Depan',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Irfan Muhtadi',
                'email' => 'irfanmuhtadi454@gmail.com',
                'phone' => '081264573883',
                'join_date' => '2024-10-30 17:00:15',
                'position' => 'GK, Belakang, Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Keko Yogaswara',
                'email' => 'kyogasadewa@gmail.com',
                'phone' => '085711189737',
                'join_date' => '2024-10-30 17:08:30',
                'position' => 'Depan',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Eki Soc',
                'email' => 'ekisoc@gmail.com',
                'phone' => '085718180204',
                'join_date' => '2024-10-30 19:58:30',
                'position' => 'Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Huda Prasetyo',
                'email' => 'hudaprasetyo20@gmail.com',
                'phone' => '089665516168',
                'join_date' => '2024-10-30 20:57:15',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Arfian Ramadhoni',
                'email' => 'afrian.ramadhoni89@gmail.com',
                'phone' => '087856410612',
                'join_date' => '2024-10-31 00:23:12',
                'position' => 'GK',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Arief Rahman Hakim',
                'email' => 'ariefjunior06@gmail.com',
                'phone' => '089678788972',
                'join_date' => '2024-10-31 03:50:23',
                'position' => 'GK',
                'jersey' => 'Putih',
            ],
            [
                'name' => 'Ega Wafiq',
                'email' => 'egawafiq7@gmail.com',
                'phone' => '087876294703',
                'join_date' => '2024-10-31 08:22:47',
                'position' => 'Tengah',
                'jersey' => 'Biru, Gold, Merah, Putih',
            ],
            [
                'name' => 'Nanda Prasetyo',
                'email' => 'nandaadeprasetyo@gmail.com',
                'phone' => '0817890511',
                'join_date' => '2024-10-31 08:22:47',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Anzhari Budiono',
                'email' => 'anzharibudiono@gmail.com',
                'phone' => '081288378515',
                'join_date' => '2024-10-31 08:22:47',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Ivan Kurnia',
                'email' => 'ivankurnia96@gmail.com',
                'phone' => '081310607920',
                'join_date' => '2024-10-31 08:22:47',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Legor',
                'email' => 'legor@gmail.com',
                'phone' => '08567628810',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'GK',
                'jersey' => 'Merah, Putih',
            ],
            [
                'name' => 'Awan Setiawan',
                'email' => 'awansetiawan38.sta@gmail.com',
                'phone' => '081285778151',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Hasan Basri',
                'email' => 'bonabasri@gmail.com',
                'phone' => '081286698958',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Saddam M',
                'email' => 'marnasihcute140747@gmail.com',
                'phone' => '081268867004',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'ISWADI',
                'email' => 'iswadi666@gmail.com',
                'phone' => '085773977779',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Maruin',
                'email' => 'maruin1991@gmail.com',
                'phone' => '081296663512',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Tengah, Depan',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Irfan Abdillah',
                'email' => 'irfanabdillah809@gmail.com',
                'phone' => '083132435300',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Gold, Merah, Putih',
            ],
            [
                'name' => 'Arga Putra Rachman',
                'email' => 'argaputra.rachman@gmail.com',
                'phone' => '081284008224',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Azmi',
                'email' => 'azminazmi10@gmail.com',
                'phone' => '089636442206',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Teubri Goathete',
                'email' => 'teubrigoethate@gmail.com',
                'phone' => '08111114665',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Biru',
            ],
            [
                'name' => 'Dani Priasmoro Adjie',
                'email' => 'danipriasmoro@gmail.com',
                'phone' => '085715428599',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Ilo Idriss',
                'email' => 'ilobinidris@gmail.com',
                'phone' => '082219181995',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Hilmi',
                'email' => 'hilmi03051989@gmail.com',
                'phone' => '085781231267',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Windando Bimantor',
                'email' => 'winandobimantoro@gmail.com',
                'phone' => '08978383876',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Muhammad Arief Maulana',
                'email' => 'muhammad.arief.maulana.harahap@gmail.com',
                'phone' => '081316148341',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Dani Hermawan',
                'email' => 'dannyhermawan27@gmail.com',
                'phone' => '081324023475',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Biru, Gold',
            ],
            [
                'name' => 'Indra Sinaga',
                'email' => 'nagasinaga@gmail.com',
                'phone' => '08119910783',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Bangun',
                'email' => 'bangun.android@gmail.com',
                'phone' => '08569058776',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Kevin',
                'email' => 'kevinfditia@gmail.com',
                'phone' => '087887963745',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Faisal Rahman',
                'email' => 'faisal.rahman@gmail.com',
                'phone' => '081393048409',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Ivvan Dharma',
                'email' => 'ivvan.dharma@gmail.com',
                'phone' => '082298988893',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'Randy Anandhita',
                'email' => 'randy.anandhita@gmail.com',
                'phone' => '081330407273',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
            [
                'name' => 'hasansland',
                'email' => 'hasansland@gmail.com',
                'phone' => '085728096396',
                'join_date' => '2025-01-31 08:22:47',
                'position' => 'Belakang, Tengah',
                'jersey' => 'Tidak Punya Semua',
            ],
        ];

        foreach ($data as $row) {
            $user = User::create([
                'name' => $row['name'],
                'email' => $row['email'],
                'phone' => $row['phone'],
                'password' => Hash::make($row['phone']),
                'join_date' => Carbon::parse($row['join_date']),
            ]);

            CommunityMember::create([
                'user_id' => $user->id,
                'community_id' => 1,
                'join_date' => Carbon::parse($row['join_date']),
                'position' => $row['position'],
                'jersey' => $row['jersey'],
            ]);
        }
    }
}
